FROM redis:8.4.0

# Currently unused configuration
# For demonstrating my Redis clone project

# FROM rust:1.89 AS builder
# WORKDIR /app
# RUN git clone https://github.com/thomascpowell/redis.git .
# RUN cargo build --release
#
# FROM debian:bookworm-slim
# WORKDIR /app
# COPY --from=builder /app/target/release/redis .
#
# EXPOSE 6379
# CMD ["./redis", "0.0.0.0:6379"]
